function plot_dynamic_hit_pareto( ...
    tableP1, tableP2, baselineTable, outputPath)
%PLOT_DYNAMIC_HIT_PARETO Goodput versus calibrated empirical jam-hit.

    figure;
    tiledlayout(1, 2);

    nexttile;
    hold on;

    nonPareto = ~tableP1.IsPareto;
    scatter( ...
        tableP1.EmpiricalJamHit(nonPareto), ...
        tableP1.GoodputMbps(nonPareto), ...
        48, "filled", ...
        "DisplayName", "D-PACT dominated points");

    scatter( ...
        tableP1.EmpiricalJamHit(tableP1.IsPareto), ...
        tableP1.GoodputMbps(tableP1.IsPareto), ...
        70, "filled", ...
        "DisplayName", "D-PACT Pareto points");

    scatter( ...
        baselineTable.EmpiricalJamHit, ...
        baselineTable.GoodputMbps, ...
        90, "d", ...
        "LineWidth", 1.2, ...
        "DisplayName", "Reference baselines");

    for index = 1:height(tableP2)
        text( ...
            tableP2.EmpiricalJamHit(index), ...
            tableP2.GoodputMbps(index), ...
            "  " + tableP2.Label(index) ...
            + sprintf(" (%.3g, %.3g)", ...
                tableP2.Beta(index), tableP2.Nu(index)), ...
            "FontSize", 8);
    end

    for index = 1:height(baselineTable)
        text( ...
            baselineTable.EmpiricalJamHit(index), ...
            baselineTable.GoodputMbps(index), ...
            "  " + baselineTable.Variant(index), ...
            "FontSize", 8);
    end

    xlabel("Empirical jam-hit rate");
    ylabel("Goodput (Mbps)");
    title("D-PACT calibrated hit-risk Pareto frontier");
    legend("Location", "best");
    grid on;
    hold off;

    nexttile;
    hold on;

    betaValues = unique(tableP1.Beta, "sorted");

    for betaIndex = 1:numel(betaValues)
        mask = tableP1.Beta == betaValues(betaIndex);
        subset = sortrows(tableP1(mask, :), "Nu");

        plot( ...
            subset.Nu, ...
            subset.EmpiricalJamHit, ...
            "-o", ...
            "LineWidth", 1.2, ...
            "DisplayName", ...
            sprintf("\\beta=%g", betaValues(betaIndex)));
    end

    xlabel("\nu");
    ylabel("Empirical jam-hit rate");
    title("Risk sensitivity across \beta and \nu");
    legend("Location", "best");
    grid on;
    hold off;

    saveas(gcf, outputPath);

end
