function plot_dynamic_safe_frontier( ...
    tableS1, tableS2, unconstrained, outputPath)
%PLOT_DYNAMIC_SAFE_FRONTIER Publication-oriented safe frontier.

    figure( ...
        "Units", "inches", ...
        "Position", [1, 1, 7.4, 5.2]);

    hold on;

    scatter( ...
        tableS1.EmpiricalJamHit, ...
        tableS1.GoodputMbps, ...
        58, "filled", ...
        "DisplayName", "D-PACT-Safe");

    frontier = sortrows( ...
        tableS1(tableS1.IsPareto, :), ...
        "EmpiricalJamHit");

    plot( ...
        frontier.EmpiricalJamHit, ...
        frontier.GoodputMbps, ...
        "-", ...
        "LineWidth", 1.4, ...
        "DisplayName", "Safe Pareto frontier");

    scatter( ...
        unconstrained.summary.meanJamHitRate, ...
        unconstrained.summary.meanGoodputMbps, ...
        80, "d", ...
        "LineWidth", 1.4, ...
        "DisplayName", "D-PACT-Hit");

    for index = 1:height(tableS2)
        text( ...
            tableS2.EmpiricalJamHit(index), ...
            tableS2.GoodputMbps(index), ...
            "  " + tableS2.Label(index), ...
            "FontSize", 9, ...
            "VerticalAlignment", "bottom");
    end

    xlabel("Empirical jam-hit rate");
    ylabel("Goodput (Mbps)");
    title("Risk-constrained D-PACT operating frontier");
    legend("Location", "best");
    grid on;
    box on;
    hold off;

    export_or_save(gcf, outputPath);

end


function export_or_save(fig, outputPath)

    try
        exportgraphics(fig, outputPath, ...
            "Resolution", 300);
    catch
        saveas(fig, outputPath);
    end

end
