function plot_paper_c6_summary(tableC6, outputPath)
%PLOT_PAPER_C6_SUMMARY Selected-method scaling figure.

    learners = [ ...
        "LC-Tsallis-INF-Online"; ...
        "Risk-aware EXP4"; ...
        "D-PACT-AFH"; ...
        "D-PACT-Safe95"];

    figure( ...
        "Units", "inches", ...
        "Position", [1, 1, 8.4, 6.2]);

    layout = tiledlayout(2, 2, ...
        "TileSpacing", "compact", ...
        "Padding", "compact");

    handles = plot_panel( ...
        tableC6, learners, "K", "GoodputMbps", ...
        "Number of channels K", ...
        "Goodput (Mbps)", ...
        "Goodput scaling with K");

    plot_panel( ...
        tableC6, learners, "K", "EmpiricalJamHit", ...
        "Number of channels K", ...
        "Empirical jam-hit", ...
        "Risk scaling with K");

    plot_panel( ...
        tableC6, learners, "T", "GoodputMbps", ...
        "Horizon T", ...
        "Goodput (Mbps)", ...
        "Goodput scaling with T");

    plot_panel( ...
        tableC6, learners, "T", "RuntimeSeconds", ...
        "Horizon T", ...
        "Runtime (s)", ...
        "Runtime scaling with T");

    firstAxes = findobj(gcf, "Type", "axes");
    firstAxes = firstAxes(end);

    legend(firstAxes, handles, ...
        shorten_learner(learners), ...
        "Location", "southoutside", ...
        "Orientation", "horizontal");

    title(layout, "Communication and computational scaling");

    export_or_save(gcf, outputPath);

end


function handles = plot_panel( ...
    input, learners, scaleType, fieldName, ...
    xLabelText, yLabelText, titleText)

    ax = nexttile;
    hold(ax, "on");

    handles = gobjects(numel(learners), 1);

    for index = 1:numel(learners)

        mask = input.ScaleType == scaleType ...
            & input.Learner == learners(index);

        subset = sortrows(input(mask, :), "ScaleValue");

        handles(index) = plot( ...
            ax, ...
            subset.ScaleValue, ...
            subset.(char(fieldName)), ...
            "-o", ...
            "LineWidth", 1.15, ...
            "MarkerSize", 5);
    end

    xlabel(ax, xLabelText);
    ylabel(ax, yLabelText);
    title(ax, titleText);
    grid(ax, "on");
    box(ax, "on");
    hold(ax, "off");

end


function output = shorten_learner(input)

    output = string(input);

    replacements = [
        "LC-Tsallis-INF-Online", "LC-INF"
        "Risk-aware EXP4", "RA-EXP4"
        "D-PACT-AFH", "D-PACT-Hit"
        "D-PACT-Safe95", "D-PACT-Safe"
    ];

    for index = 1:size(replacements, 1)
        output(output == replacements(index, 1)) = ...
            replacements(index, 2);
    end

end


function export_or_save(fig, outputPath)

    try
        exportgraphics(fig, outputPath, "Resolution", 300);
    catch
        saveas(fig, outputPath);
    end

end
