function multiResults = aggregate_seed_records( ...
    records, cfg, learnerType, adversaryType)
%AGGREGATE_SEED_RECORDS Convert checkpoint records to legacy result shape.

    numSeeds = numel(records);
    seedList = zeros(1, numSeeds);
    allResults = cell(numSeeds, 1);
    allMetrics = cell(numSeeds, 1);

    names = [ ...
        "avgReward", "avgRate", "avgGoodputMbps", ...
        "adaptiveGoodputMbps", "cappedGoodputMbps", ...
        "fixedGoodputMbps", "pdr", "meanSinrDb", "avgBer", ...
        "switchingRate", "retransmissionRate", ...
        "fixedArmRegret", "dynamicOracleRegret", ...
        "roundsTo90Goodput", "avgOverlap", ...
        "predictionHitRate", "avgRiskAtAction", ...
        "expectedJamHit", "avgHitRiskAtAction", ...
        "jamCalibrationGap", "actionRiskCalibrationGap", ...
        "jamHitRate", "occHitRate", ...
        "avgLegacyEffectiveReward", "avgLegacyEffectiveLoss", ...
        "actionEntropy", "runtime", "avgBaseRisk", ...
        "avgExplorationRisk", "avgBaseExplorationRisk", ...
        "sigmaRcond", "maxThetaHatNorm", ...
        "effectiveExpertCount", "uniformExpertMass", ...
        "coarseScaleMass", "mediumScaleMass", "fineScaleMass", ...
        "linearFamilyMass", "partitionFamilyMass", ...
        "predictorRegret", "predictorGain", ...
        "folpettiSuccessRate", ...
        "masterLcMass", "masterLocalMass", ...
        "masterEffectiveCount", ...
        "maxLcOffPolicyRatio", "maxLocalOffPolicyRatio", ...
        "riskProjectionActivationRate", ...
        "avgRiskProjectionKl", ...
        "avgPreProjectionHitRisk", ...
        "avgPostProjectionHitRisk", ...
        "maxRiskProjectionViolation"];

    data = struct();
    for index = 1:numel(names)
        data.(char(names(index))) = NaN(numSeeds, 1);
    end

    for seedIndex = 1:numSeeds
        record = records{seedIndex};
        metrics = record.metrics;
        diagnostics = record.diagnostics;

        seedList(seedIndex) = record.seed;
        allResults{seedIndex} = record.results;
        allMetrics{seedIndex} = record.metrics;

        data.avgReward(seedIndex) = metrics.finalAvgReward;
        data.avgRate(seedIndex) = metrics.finalAvgRate;
        data.avgGoodputMbps(seedIndex) = metrics.finalAvgGoodputMbps;
        data.adaptiveGoodputMbps(seedIndex) = ...
            metrics.finalAvgAdaptiveGoodputMbps;
        data.cappedGoodputMbps(seedIndex) = ...
            metrics.finalAvgCappedGoodputMbps;
        data.fixedGoodputMbps(seedIndex) = ...
            metrics.finalAvgFixedGoodputMbps;
        data.pdr(seedIndex) = metrics.finalPdr;
        data.meanSinrDb(seedIndex) = metrics.finalMeanSinrDb;
        data.avgBer(seedIndex) = metrics.finalAvgBer;
        data.switchingRate(seedIndex) = metrics.finalSwitchingRate;
        data.retransmissionRate(seedIndex) = ...
            metrics.finalRetransmissionRate;
        data.fixedArmRegret(seedIndex) = metrics.finalFixedArmRegret;
        data.dynamicOracleRegret(seedIndex) = ...
            metrics.finalDynamicOracleRegret;
        if isfield(metrics, "roundsTo90PercentFinalGoodput")
            data.roundsTo90Goodput(seedIndex) = ...
                metrics.roundsTo90PercentFinalGoodput;
        else
            data.roundsTo90Goodput(seedIndex) = NaN;
        end
        data.avgOverlap(seedIndex) = metrics.finalAvgOverlap;
        data.predictionHitRate(seedIndex) = ...
            metrics.finalPredictionHitRate;
        data.avgRiskAtAction(seedIndex) = ...
            metrics.finalAvgRiskAtAction;
        data.expectedJamHit(seedIndex) = ...
            metrics.finalAvgExpectedJamHit;
        data.avgHitRiskAtAction(seedIndex) = ...
            metrics.finalAvgHitRiskAtAction;
        data.jamCalibrationGap(seedIndex) = ...
            metrics.finalExpectedJamHitCalibrationGap;
        data.actionRiskCalibrationGap(seedIndex) = ...
            metrics.finalActionRiskCalibrationGap;
        data.jamHitRate(seedIndex) = metrics.finalJamHitRate;
        data.occHitRate(seedIndex) = metrics.finalOccHitRate;
        data.avgLegacyEffectiveReward(seedIndex) = ...
            metrics.finalAvgLegacyEffectiveReward;
        data.avgLegacyEffectiveLoss(seedIndex) = ...
            metrics.finalAvgLegacyEffectiveLoss;
        data.actionEntropy(seedIndex) = metrics.normalizedActionEntropy;
        data.runtime(seedIndex) = record.runtime;

        if isfield(metrics, "finalRiskProjectionActivationRate")
            data.riskProjectionActivationRate(seedIndex) = ...
                metrics.finalRiskProjectionActivationRate;
            data.avgRiskProjectionKl(seedIndex) = ...
                metrics.finalAvgRiskProjectionKl;
            data.avgPreProjectionHitRisk(seedIndex) = ...
                metrics.finalAvgPreProjectionHitRisk;
            data.avgPostProjectionHitRisk(seedIndex) = ...
                metrics.finalAvgPostProjectionHitRisk;
            data.maxRiskProjectionViolation(seedIndex) = ...
                metrics.finalMaxRiskProjectionViolation;
        end

        data.avgBaseRisk(seedIndex) = diagnostics.avgBaseRisk;
        data.avgExplorationRisk(seedIndex) = ...
            diagnostics.avgExplorationRisk;
        data.avgBaseExplorationRisk(seedIndex) = ...
            diagnostics.avgBaseExplorationRisk;

        diagnosticNames = fieldnames(diagnostics);
        for d = 1:numel(diagnosticNames)
            name = diagnosticNames{d};
            if isfield(data, name)
                data.(name)(seedIndex) = diagnostics.(name);
            end
        end
    end

    summary.learnerType = string(learnerType);
    summary.adversaryType = string(adversaryType);
    summary.environmentRegime = get_optional_string( ...
        cfg, "environment_regime", "stochastic");
    summary.rewardMode = get_optional_string( ...
        cfg, "reward_mode", "outage_capped");
    summary.numSeeds = numSeeds;

    labels = [ ...
        "AvgReward", "AvgRate", "GoodputMbps", ...
        "AdaptiveGoodputMbps", "CappedGoodputMbps", ...
        "FixedGoodputMbps", "Pdr", "MeanSinrDb", "AvgBer", ...
        "SwitchingRate", "RetransmissionRate", ...
        "FixedArmRegret", "DynamicOracleRegret", ...
        "RoundsTo90Goodput", "Overlap", "PredictionHitRate", ...
        "RiskAtAction", "ExpectedJamHit", "HitRiskAtAction", ...
        "JamCalibrationGap", "ActionRiskCalibrationGap", ...
        "JamHitRate", "OccHitRate", ...
        "BaseRisk", "ExplorationRisk", "BaseExplorationRisk", ...
        "ActionEntropy", "EffectiveExpertCount", ...
        "UniformExpertMass", "CoarseScaleMass", ...
        "MediumScaleMass", "FineScaleMass", ...
        "LinearFamilyMass", "PartitionFamilyMass", ...
        "PredictorRegret", "PredictorGain", ...
        "FolpettiSuccessRate", ...
        "MasterLcMass", "MasterLocalMass", ...
        "MasterEffectiveCount", ...
        "MaxLcOffPolicyRatio", "MaxLocalOffPolicyRatio", ...
        "RiskProjectionActivationRate", ...
        "AvgRiskProjectionKl", ...
        "AvgPreProjectionHitRisk", ...
        "AvgPostProjectionHitRisk", ...
        "MaxRiskProjectionViolation"];

    sourceNames = [ ...
        "avgReward", "avgRate", "avgGoodputMbps", ...
        "adaptiveGoodputMbps", "cappedGoodputMbps", ...
        "fixedGoodputMbps", "pdr", "meanSinrDb", "avgBer", ...
        "switchingRate", "retransmissionRate", ...
        "fixedArmRegret", "dynamicOracleRegret", ...
        "roundsTo90Goodput", "avgOverlap", "predictionHitRate", ...
        "avgRiskAtAction", "expectedJamHit", ...
        "avgHitRiskAtAction", "jamCalibrationGap", ...
        "actionRiskCalibrationGap", "jamHitRate", "occHitRate", ...
        "avgBaseRisk", "avgExplorationRisk", ...
        "avgBaseExplorationRisk", "actionEntropy", ...
        "effectiveExpertCount", "uniformExpertMass", ...
        "coarseScaleMass", "mediumScaleMass", "fineScaleMass", ...
        "linearFamilyMass", "partitionFamilyMass", ...
        "predictorRegret", "predictorGain", "folpettiSuccessRate", ...
        "masterLcMass", "masterLocalMass", ...
        "masterEffectiveCount", ...
        "maxLcOffPolicyRatio", "maxLocalOffPolicyRatio", ...
        "riskProjectionActivationRate", ...
        "avgRiskProjectionKl", ...
        "avgPreProjectionHitRisk", ...
        "avgPostProjectionHitRisk", ...
        "maxRiskProjectionViolation"];

    for index = 1:numel(labels)
        summary = add_summary(summary, labels(index), ...
            data.(char(sourceNames(index))));
    end

    summary.meanRuntime = mean(data.runtime, "omitnan");
    summary.totalRuntime = sum(data.runtime, "omitnan");

    multiResults.seedList = seedList;
    multiResults.learnerType = string(learnerType);
    multiResults.adversaryType = string(adversaryType);
    multiResults.environmentRegime = summary.environmentRegime;
    multiResults.allResults = allResults;
    multiResults.allMetrics = allMetrics;

    fields = fieldnames(data);
    for index = 1:numel(fields)
        multiResults.(fields{index}) = data.(fields{index});
    end

    multiResults.avgEffectiveReward = data.avgLegacyEffectiveReward;
    multiResults.avgEffectiveLoss = data.avgLegacyEffectiveLoss;
    multiResults.summary = summary;

end


function summary = add_summary(summary, label, values)

    values = values(:);
    values = values(isfinite(values));
    if isempty(values)
        meanValue = NaN; stdValue = NaN; ci95 = NaN;
    else
        meanValue = mean(values);
        stdValue = std(values);
        ci95 = 1.96 * stdValue / sqrt(numel(values));
    end

    summary.(char("mean" + label)) = meanValue;
    summary.(char("std" + label)) = stdValue;
    summary.(char("ci95" + label)) = ci95;

end


function value = get_optional_string(inputStruct, fieldName, defaultValue)

    fieldName = char(fieldName);
    if isfield(inputStruct, fieldName)
        value = string(inputStruct.(fieldName));
    else
        value = string(defaultValue);
    end

end
