function suite = get_dynamic_c5_c6_config(mode)
%GET_DYNAMIC_C5_C6_CONFIG Final environment and scaling experiments.

    if nargin < 1
        mode = "quick";
    end

    mode = lower(string(mode));
    suite.mode = mode;

    switch mode
        case "smoke"
            suite.c5T = 300;
            suite.c5Seeds = 98001:98002;

            suite.c6KScalingT = 300;
            suite.c6KGrid = [8, 12];
            suite.c6TGrid = [300, 600];
            suite.c6Seeds = 98101:98102;

        case "quick"
            suite.c5T = 3000;
            suite.c5Seeds = 98001:98006;

            suite.c6KScalingT = 3000;
            suite.c6KGrid = [8, 12, 16];
            suite.c6TGrid = [1000, 3000, 5000];
            suite.c6Seeds = 98101:98104;

        case "full"
            suite.c5T = 10000;
            suite.c5Seeds = 98001:98020;

            suite.c6KScalingT = 10000;
            suite.c6KGrid = [8, 12, 16, 32];
            suite.c6TGrid = [1000, 5000, 10000, 20000];
            suite.c6Seeds = 98101:98110;

        otherwise
            error("Unknown C5/C6 mode: %s", mode);
    end

    suite.attackBudget = 1;
    suite.beta = 16;
    suite.nu = 0;
    suite.safeLabel = "safe95";

    suite.c5OutputRoot = fullfile( ...
        "results", "dynamic_c5", char(mode));

    suite.c6OutputRoot = fullfile( ...
        "results", "dynamic_c6", char(mode));

    suite.c5RegimeLabels = [ ...
        "Nominal"; ...
        "Nonlinear interaction"; ...
        "Observable switching"; ...
        "White-box"; ...
        "Contaminated"; ...
        "Exogenous sweep"; ...
        "Mixed"; ...
        "Hidden Markov"];

    suite.c5EnvironmentRegimes = [ ...
        "stochastic"; ...
        "nonlinear_interaction"; ...
        "observable_switching"; ...
        "stochastic"; ...
        "contaminated_stochastic"; ...
        "oblivious_sweep"; ...
        "mixed"; ...
        "hidden_markov"];

    suite.c5Adversaries = [ ...
        "none"; ...
        "none"; ...
        "none"; ...
        "contextual_expert"; ...
        "contextual_expert"; ...
        "contextual_expert"; ...
        "contextual_expert"; ...
        "contextual_expert"];

    suite.learners = [ ...
        "lc_inf_online"; ...
        "risk_exp4"; ...
        "aufh_exp3pp"; ...
        "dpact_nodetect"; ...
        "dpact_detect"; ...
        "dpact_safe"];

end
