function suite = get_final_c1_c4_config(mode)
%GET_FINAL_C1_C4_CONFIG Final paper C1-C4 experiment configuration.
%
% The final operating point is frozen at beta=16, nu=0. Safe95 is
% resolved from the full safe projection scan, with tau=0.11 only as an
% explicit fallback.

    if nargin < 1
        mode = "quick";
    end

    mode = lower(string(mode));
    suite.mode = mode;

    switch mode
        case "smoke"
            suite.T = 300;
            suite.c2Seeds = 99101:99102;
            suite.c3Seeds = 99201:99202;
            suite.c4Seeds = 99301:99302;
            suite.folpettiMcSamples = 64;

        case "quick"
            suite.T = 3000;
            suite.c2Seeds = 99101:99106;
            suite.c3Seeds = 99201:99206;
            suite.c4Seeds = 99301:99306;
            suite.folpettiMcSamples = 256;

        case "full"
            suite.T = 10000;
            suite.c2Seeds = 99101:99120;
            suite.c3Seeds = 99201:99220;
            suite.c4Seeds = 99301:99320;
            suite.folpettiMcSamples = 512;

        otherwise
            error("Unknown final C1-C4 mode: %s", mode);
    end

    suite.beta = 16;
    suite.nu = 0;
    suite.attackBudget = 1;
    suite.safeLabel = "safe95";
    suite.safeFallbackTau = 0.11;
    suite.mainAdversary = "contextual_expert";

    suite.c2Learners = [ ...
        "ucb", ...
        "ts", ...
        "exp3", ...
        "lc_inf_online", ...
        "risk_exp4", ...
        "aufh_exp3pp", ...
        "dpact_nodetect", ...
        "dpact_detect", ...
        "dpact_safe"];

    suite.c2CurveLearners = [ ...
        "lc_inf_online", ...
        "risk_exp4", ...
        "aufh_exp3pp", ...
        "dpact_nodetect", ...
        "dpact_detect", ...
        "dpact_safe"];

    suite.c3Adversaries = [ ...
        "random", ...
        "sweep", ...
        "folpetti_ts", ...
        "contextual_expert"];

    suite.c3Learners = [ ...
        "ts", ...
        "exp3", ...
        "lc_inf_online", ...
        "risk_exp4", ...
        "aufh_exp3pp", ...
        "dpact_nodetect", ...
        "dpact_detect", ...
        "dpact_safe"];

    suite.c4Labels = [ ...
        "D-PACT LC-only"; ...
        "D-PACT Local-only"; ...
        "D-PACT-Base"; ...
        "D-PACT-Hit"; ...
        "D-PACT-Safe95"];

    suite.c4Learners = [ ...
        "dpact_nodetect"; ...
        "dpact_nodetect"; ...
        "dpact_nodetect"; ...
        "dpact_detect"; ...
        "dpact_safe"];

    suite.c4ForceBase = [ ...
        "lc"; ...
        "local"; ...
        "none"; ...
        "none"; ...
        "none"];

end
