function row = build_communication_summary_row( ...
    multiResults, extra)
%BUILD_COMMUNICATION_SUMMARY_ROW One publication-style summary row.

    if nargin < 2
        extra = struct();
    end

    summary = multiResults.summary;

    row = table( ...
        get_learner_display_name(multiResults.learnerType), ...
        get_adversary_display_name(multiResults.adversaryType), ...
        string(multiResults.environmentRegime), ...
        string(summary.rewardMode), ...
        summary.meanAvgReward, ...
        summary.ci95AvgReward, ...
        summary.meanGoodputMbps, ...
        summary.ci95GoodputMbps, ...
        summary.meanAdaptiveGoodputMbps, ...
        summary.meanCappedGoodputMbps, ...
        summary.meanFixedGoodputMbps, ...
        summary.meanPdr, ...
        summary.ci95Pdr, ...
        summary.meanMeanSinrDb, ...
        summary.ci95MeanSinrDb, ...
        summary.meanJamHitRate, ...
        summary.ci95JamHitRate, ...
        summary.meanOverlap, ...
        summary.ci95Overlap, ...
        summary.meanSwitchingRate, ...
        summary.ci95SwitchingRate, ...
        summary.meanFixedArmRegret, ...
        summary.ci95FixedArmRegret, ...
        summary.meanRuntime, ...
        'VariableNames', { ...
            'Learner', 'Adversary', 'Regime', 'RewardMode', ...
            'Reward', 'RewardCI95', ...
            'GoodputMbps', 'GoodputCI95', ...
            'AdaptiveGoodputMbps', ...
            'CappedGoodputMbps', ...
            'FixedGoodputMbps', ...
            'PDR', 'PDRCI95', ...
            'MeanSINRdB', 'MeanSINRdBCI95', ...
            'JamHit', 'JamHitCI95', ...
            'Overlap', 'OverlapCI95', ...
            'SwitchingRate', 'SwitchingRateCI95', ...
            'FixedArmRegret', 'FixedArmRegretCI95', ...
            'RuntimeSeconds'});

    extraNames = fieldnames(extra);
    for index = 1:numel(extraNames)
        fieldName = extraNames{index};
        value = extra.(fieldName);
        if ischar(value)
            value = string(value);
        end
        row.(fieldName) = value;
    end

end
