function write_final_report( ...
    outputPath, tableModel, tableC5Claims, ...
    safeIncluded, c6Included)
%WRITE_FINAL_REPORT Write a numerical paper-claim report.

    fileId = fopen(outputPath, "w");

    if fileId < 0
        error("Could not open %s.", outputPath);
    end

    cleanup = onCleanup(@() fclose(fileId));

    fprintf(fileId, "# Final communication results\\n\\n");

    observable = tableModel( ...
        tableModel.Regime == "Observable switching", :);

    nonlinear = tableModel( ...
        tableModel.Regime == "Nonlinear interaction", :);

    fprintf(fileId, "## Dynamic model selection\\n\\n");

    fprintf(fileId, ...
        "- Observable switching: Local-only improves goodput by " ...
        + "**%.3f +/- %.3f Mbps** relative to LC.\\n", ...
        observable.LocalMinusLCGoodputMbps, ...
        observable.LocalMinusLCGoodputCI95);

    fprintf(fileId, ...
        "- Dynamic D-PACT improves goodput by " ...
        + "**%.3f +/- %.3f Mbps**, assigns **%.1f%%** mass to Local, " ...
        + "and recovers **%.1f%%** of the Local-only gain.\\n", ...
        observable.DynamicMinusLCGoodputMbps, ...
        observable.DynamicMinusLCGoodputCI95, ...
        100 * observable.DynamicLocalMass, ...
        observable.RecoveryPercent);

    fprintf(fileId, ...
        "- Nonlinear QoS: Local-only changes goodput by " ...
        + "**%.3f +/- %.3f Mbps**. Dynamic D-PACT limits the change to " ...
        + "**%.3f +/- %.3f Mbps**, mitigating **%.1f%%** of the " ...
        + "Local-only loss.\\n\\n", ...
        nonlinear.LocalMinusLCGoodputMbps, ...
        nonlinear.LocalMinusLCGoodputCI95, ...
        nonlinear.DynamicMinusLCGoodputMbps, ...
        nonlinear.DynamicMinusLCGoodputCI95, ...
        nonlinear.LossMitigationPercent);

    fprintf(fileId, "## Communication and risk claims\\n\\n");

    for index = 1:height(tableC5Claims)

        fprintf(fileId, ...
            "- %s / %s vs. %s: goodput change **%+.3f Mbps " ...
            + "(%+.1f%%)**; jam-hit change **%+.3f (%+.1f%%)**.\\n", ...
            tableC5Claims.Regime(index), ...
            tableC5Claims.Treatment(index), ...
            tableC5Claims.Reference(index), ...
            tableC5Claims.GoodputDifferenceMbps(index), ...
            tableC5Claims.GoodputRelativePercent(index), ...
            tableC5Claims.JamHitDifference(index), ...
            tableC5Claims.JamHitRelativePercent(index));
    end

    fprintf(fileId, "\\n## Included final modules\\n\\n");
    fprintf(fileId, "- Model-selection full results: yes\\n");
    fprintf(fileId, "- C5 full results: yes\\n");
    fprintf(fileId, "- Safe frontier: %s\\n", yes_no(safeIncluded));
    fprintf(fileId, "- C6 scaling: %s\\n", yes_no(c6Included));

    fprintf(fileId, ...
        "\\nAll percentages are computed from the stored full-result " ...
        + "tables. Confidence intervals remain in the accompanying CSV " ...
        + "and LaTeX tables.\\n");

end


function output = yes_no(value)

    if value
        output = "yes";
    else
        output = "not found";
    end

end
