clear; clc; close all;

setup_paths();

probePath = fullfile( ...
    "results", ...
    "dynamic_model_class_probe", ...
    "full", ...
    "raw", ...
    "C5M_model_class_probe.mat");

c5Path = fullfile( ...
    "results", ...
    "dynamic_c5", ...
    "full", ...
    "raw", ...
    "C5_dynamic_safe.mat");

assert(isfile(probePath), ...
    "Run the full model-class probe first.");

assert(isfile(c5Path), ...
    "Run C5 full first.");

outputs = finalize_communication_results("full");

assert(istable(outputs.tableModel));
assert(istable(outputs.tableC5Main));
assert(istable(outputs.tableC5Claims));

observable = outputs.tableModel( ...
    outputs.tableModel.Regime == ...
    "Observable switching", :);

assert(observable.DynamicMinusLCGoodputMbps > 0);
assert(observable.DynamicLocalMass > 0.5);

disp("Final paper package test passed.");
