function outputs = run_pact_model_diagnostics(mode)
%RUN_PACT_MODEL_DIAGNOSTICS Diagnose linearity, expressivity, and learning.
%
% This suite answers four questions before changing the main algorithm:
%
% D1. Is the current communication environment effectively linear-friendly?
% D2. Is the current PACT expert class expressive enough?
% D3. Is the online gap caused by expert representation, aggregation,
%     exploration, or learning-rate choice?
% D4. Do the current "partition" experts actually represent common
%     nonlinear structures such as XOR, band-pass, and regime flips?
%
% Examples:
%   outputs = run_pact_model_diagnostics("smoke");
%   outputs = run_pact_model_diagnostics("quick");
%   outputs = run_pact_model_diagnostics("full");

    if nargin < 1
        mode = "quick";
    end

    projectRoot = setup_paths();
    diagCfg = get_model_diagnostic_config(mode);

    outputRoot = fullfile(projectRoot, diagCfg.outputRoot);
    tableFolder = fullfile(outputRoot, "tables");
    figureFolder = fullfile(outputRoot, "figures");
    rawFolder = fullfile(outputRoot, "raw");
    checkpointFolder = fullfile(outputRoot, "checkpoints");

    ensure_folder(tableFolder);
    ensure_folder(figureFolder);
    ensure_folder(rawFolder);
    ensure_folder(checkpointFolder);

    cfg = get_base_config();
    cfg.T = diagCfg.T;
    cfg.seedList = diagCfg.seedList;
    cfg.numSeeds = numel(diagCfg.seedList);
    cfg.checkpoint_root = checkpointFolder;
    cfg.resume = true;
    cfg.use_parallel = true;
    cfg.store_full_histories = true;
    cfg.store_metric_timeseries = true;
    cfg.reward_mode = "outage_capped";

    fprintf("\n########################################\n");
    fprintf("PACT-AFH model diagnostics: %s\n", mode);
    fprintf("T = %d, seeds = %d\n", ...
        cfg.T, numel(cfg.seedList));
    fprintf("Output: %s\n", outputRoot);
    fprintf("########################################\n");

    %% D1. Current-environment linearity
    fprintf("\n===== D1: Environment linearity =====\n");

    rawD1 = cell( ...
        numel(diagCfg.oracleScenarios) ...
        * numel(diagCfg.seedList) * 2, 1);

    rawD2 = cell( ...
        numel(diagCfg.oracleScenarios) ...
        * numel(diagCfg.seedList) * 3, 1);

    d1Index = 0;
    d2Index = 0;

    for scenarioIndex = 1:numel(diagCfg.oracleScenarios)

        scenario = diagCfg.oracleScenarios(scenarioIndex);

        for seedIndex = 1:numel(diagCfg.seedList)

            seed = diagCfg.seedList(seedIndex);

            dataset = build_diagnostic_dataset( ...
                cfg, seed, scenario);

            trainEnd = max(1, floor( ...
                diagCfg.trainFraction * cfg.T));

            trainMask = dataset.roundIndex <= trainEnd;
            testMask = dataset.roundIndex > trainEnd;

            for basisType = ["linear", "nonlinear"]

                model = fit_diagnostic_ridge( ...
                    dataset.features(trainMask, :), ...
                    dataset.reward(trainMask), ...
                    basisType, ...
                    diagCfg.ridgeLambda);

                modelMetrics = ...
                    evaluate_diagnostic_reward_model( ...
                        model, ...
                        dataset.features(testMask, :), ...
                        dataset.reward(testMask), ...
                        dataset.roundIndex(testMask), ...
                        dataset.armIndex(testMask), ...
                        cfg.K);

                d1Index = d1Index + 1;

                rawD1{d1Index} = table( ...
                    seed, ...
                    scenario, ...
                    basisType, ...
                    modelMetrics.rmse, ...
                    modelMetrics.r2, ...
                    modelMetrics.topArmAccuracy, ...
                    modelMetrics.meanSelectedReward, ...
                    modelMetrics.meanOracleReward, ...
                    modelMetrics.meanRankingRegret, ...
                    modelMetrics.oracleCapture, ...
                    'VariableNames', { ...
                        'Seed', ...
                        'Scenario', ...
                        'ModelClass', ...
                        'RMSE', ...
                        'R2', ...
                        'TopArmAccuracy', ...
                        'SelectedReward', ...
                        'DynamicArmReward', ...
                        'RankingRegret', ...
                        'OracleCapture'});
            end

            testRounds = (trainEnd + 1):cfg.T;

            for expertMode = ["partition", "linear", "hybrid"]

                oracle = evaluate_pact_expert_oracle( ...
                    dataset.env, ...
                    dataset.armReward, ...
                    cfg, ...
                    expertMode, ...
                    testRounds);

                d2Index = d2Index + 1;

                rawD2{d2Index} = table( ...
                    seed, ...
                    scenario, ...
                    expertMode, ...
                    oracle.numExperts, ...
                    oracle.bestFixedMean, ...
                    oracle.dynamicExpertMean, ...
                    oracle.dynamicArmMean, ...
                    oracle.fixedCapture, ...
                    oracle.dynamicExpertCapture, ...
                    string(oracle.bestFixedName), ...
                    'VariableNames', { ...
                        'Seed', ...
                        'Scenario', ...
                        'ExpertMode', ...
                        'NumExperts', ...
                        'BestFixedReward', ...
                        'DynamicExpertReward', ...
                        'DynamicArmReward', ...
                        'FixedOracleCapture', ...
                        'DynamicExpertCapture', ...
                        'BestExpertName'});
            end
        end
    end

    rawTableD1 = vertcat(rawD1{:});
    rawTableD2 = vertcat(rawD2{:});

    tableD1 = aggregate_d1(rawTableD1);
    tableD2 = aggregate_d2(rawTableD2);

    write_table_bundle(tableD1, fullfile( ...
        tableFolder, "Table_D1_environment_linearity"));

    write_table_bundle(tableD2, fullfile( ...
        tableFolder, "Table_D2_expert_oracles"));

    save(fullfile(rawFolder, "D1_D2_environment_oracles.mat"), ...
        "rawTableD1", "rawTableD2", "tableD1", "tableD2", ...
        "cfg", "diagCfg", "-v7.3");

    plot_diagnostic_linearity( ...
        tableD1, ...
        fullfile(figureFolder, ...
            "Figure_D1_environment_linearity.png"));

    plot_diagnostic_oracles( ...
        tableD2, ...
        fullfile(figureFolder, ...
            "Figure_D2_expert_oracles.png"));

    %% D3. Online backbone and optimization diagnosis
    fprintf("\n===== D3: Online backbone ablation =====\n");

    variants = diagnostic_variants();
    d3Rows = cell( ...
        numel(variants) ...
        * numel(diagCfg.onlineScenarios), 1);

    d3Raw = cell( ...
        numel(variants), ...
        numel(diagCfg.onlineScenarios));

    d3Index = 0;

    for scenarioIndex = 1:numel(diagCfg.onlineScenarios)

        adversaryType = ...
            diagCfg.onlineScenarios(scenarioIndex);

        for variantIndex = 1:numel(variants)

            variant = variants(variantIndex);
            cfgRun = apply_variant(cfg, variant);

            fprintf("\n--- %s | %s ---\n", ...
                variant.name, adversaryType);

            multiResults = run_multi_seed_pair( ...
                cfgRun, ...
                variant.learnerType, ...
                adversaryType);

            oracleSummary = evaluate_actual_run_oracle( ...
                multiResults, ...
                cfgRun, ...
                variant.oracleMode);

            meanGamma = collect_mean_gamma(multiResults);

            d3Index = d3Index + 1;

            d3Rows{d3Index} = table( ...
                variant.name, ...
                string(variant.learnerType), ...
                string(adversaryType), ...
                string(variant.expertMode), ...
                variant.gammaScale, ...
                variant.etaScale, ...
                multiResults.summary.meanAvgReward, ...
                multiResults.summary.ci95AvgReward, ...
                multiResults.summary.meanGoodputMbps, ...
                multiResults.summary.ci95GoodputMbps, ...
                multiResults.summary.meanPdr, ...
                multiResults.summary.meanOverlap, ...
                meanGamma, ...
                oracleSummary.actualMean, ...
                oracleSummary.bestFixedMean, ...
                oracleSummary.dynamicExpertMean, ...
                oracleSummary.dynamicArmMean, ...
                oracleSummary.aggregationGap, ...
                oracleSummary.representationGap, ...
                multiResults.summary.meanLinearFamilyMass, ...
                multiResults.summary.meanPartitionFamilyMass, ...
                multiResults.summary.meanRuntime, ...
                'VariableNames', { ...
                    'Variant', ...
                    'LearnerType', ...
                    'Adversary', ...
                    'ExpertMode', ...
                    'GammaScale', ...
                    'EtaScale', ...
                    'Reward', ...
                    'RewardCI95', ...
                    'GoodputMbps', ...
                    'GoodputCI95', ...
                    'PDR', ...
                    'Overlap', ...
                    'MeanGamma', ...
                    'ActualReward', ...
                    'BestFixedExpertReward', ...
                    'DynamicExpertReward', ...
                    'DynamicArmReward', ...
                    'AggregationGap', ...
                    'RepresentationGap', ...
                    'LinearFamilyMass', ...
                    'PartitionFamilyMass', ...
                    'RuntimeSeconds'});

            d3Raw{variantIndex, scenarioIndex} = multiResults;
        end
    end

    tableD3 = vertcat(d3Rows{:});

    write_table_bundle(tableD3, fullfile( ...
        tableFolder, "Table_D3_backbone_ablation"));

    save(fullfile(rawFolder, "D3_backbone_ablation.mat"), ...
        "d3Raw", "tableD3", "cfg", "diagCfg", "variants", ...
        "-v7.3");

    plot_diagnostic_backbone( ...
        tableD3, ...
        fullfile(figureFolder, ...
            "Figure_D3_backbone_ablation.png"));

    %% D4. Synthetic expressivity audit
    fprintf("\n===== D4: Synthetic expressivity audit =====\n");

    tableD4 = run_synthetic_expressivity_diagnostic( ...
        cfg, diagCfg);

    write_table_bundle(tableD4, fullfile( ...
        tableFolder, "Table_D4_synthetic_expressivity"));

    save(fullfile(rawFolder, "D4_synthetic_expressivity.mat"), ...
        "tableD4", "cfg", "diagCfg", "-v7.3");

    plot_diagnostic_expressivity( ...
        tableD4, ...
        fullfile(figureFolder, ...
            "Figure_D4_synthetic_expressivity.png"));

    %% Automated evidence summary
    reportPath = fullfile( ...
        outputRoot, "DIAGNOSTIC_VERDICT.md");

    write_diagnostic_verdict( ...
        reportPath, tableD1, tableD2, tableD3, tableD4);

    outputs.outputRoot = outputRoot;
    outputs.tableD1 = tableD1;
    outputs.tableD2 = tableD2;
    outputs.tableD3 = tableD3;
    outputs.tableD4 = tableD4;
    outputs.reportPath = reportPath;

    fprintf("\nPACT-AFH model diagnostics completed.\n");
    fprintf("Read: %s\n", reportPath);

end


function variants = diagnostic_variants()

    variants = repmat(struct( ...
        'name', "", ...
        'learnerType', "", ...
        'expertMode', "hybrid", ...
        'oracleMode', "hybrid", ...
        'gammaScale', 1.0, ...
        'etaScale', 1.0), 8, 1);

    variants(1) = make_variant( ...
        "LC-Tsallis-INF-Online", ...
        "lc_inf_online", "hybrid", "hybrid", 1.0, 1.0);

    variants(2) = make_variant( ...
        "PACT-Partition", ...
        "bc_nodetect", "partition", "partition", 1.0, 1.0);

    variants(3) = make_variant( ...
        "PACT-Linear", ...
        "bc_nodetect", "linear", "linear", 1.0, 1.0);

    variants(4) = make_variant( ...
        "PACT-Hybrid", ...
        "bc_nodetect", "hybrid", "hybrid", 1.0, 1.0);

    variants(5) = make_variant( ...
        "PACT-Hybrid-Gamma0", ...
        "bc_nodetect", "hybrid", "hybrid", 0.0, 1.0);

    variants(6) = make_variant( ...
        "PACT-Hybrid-Gamma25", ...
        "bc_nodetect", "hybrid", "hybrid", 0.25, 1.0);

    variants(7) = make_variant( ...
        "PACT-Hybrid-Eta05", ...
        "bc_nodetect", "hybrid", "hybrid", 1.0, 0.5);

    variants(8) = make_variant( ...
        "PACT-Hybrid-Eta2", ...
        "bc_nodetect", "hybrid", "hybrid", 1.0, 2.0);

end


function variant = make_variant( ...
    name, learnerType, expertMode, oracleMode, gammaScale, etaScale)

    variant.name = string(name);
    variant.learnerType = string(learnerType);
    variant.expertMode = string(expertMode);
    variant.oracleMode = string(oracleMode);
    variant.gammaScale = gammaScale;
    variant.etaScale = etaScale;

end


function cfgRun = apply_variant(cfg, variant)

    cfgRun = cfg;
    cfgRun.pact_expert_bank_mode = variant.expertMode;
    cfgRun.explore_scale = variant.gammaScale;
    cfgRun.pact_eta_scale = variant.etaScale;

end


function meanGamma = collect_mean_gamma(multiResults)

    values = NaN(numel(multiResults.allResults), 1);

    for seedIndex = 1:numel(multiResults.allResults)

        result = multiResults.allResults{seedIndex};

        if isfield(result, "learnerGamma")
            values(seedIndex) = ...
                mean(result.learnerGamma, "omitnan");
        end
    end

    meanGamma = mean(values, "omitnan");

end


function output = aggregate_d1(raw)

    scenarios = unique(raw.Scenario, "stable");
    models = unique(raw.ModelClass, "stable");

    rows = cell(numel(scenarios) * numel(models), 1);
    index = 0;

    for s = 1:numel(scenarios)
        for m = 1:numel(models)

            mask = ...
                raw.Scenario == scenarios(s) ...
                & raw.ModelClass == models(m);

            index = index + 1;

            rows{index} = summary_row_d1( ...
                scenarios(s), models(m), raw(mask, :));
        end
    end

    output = vertcat(rows{:});

end


function row = summary_row_d1(scenario, modelClass, subset)

    [rmse, rmseCI] = mean_ci(subset.RMSE);
    [r2, r2CI] = mean_ci(subset.R2);
    [accuracy, accuracyCI] = ...
        mean_ci(subset.TopArmAccuracy);
    [capture, captureCI] = ...
        mean_ci(subset.OracleCapture);
    [regret, regretCI] = ...
        mean_ci(subset.RankingRegret);

    row = table( ...
        scenario, modelClass, ...
        rmse, rmseCI, ...
        r2, r2CI, ...
        accuracy, accuracyCI, ...
        capture, captureCI, ...
        regret, regretCI, ...
        'VariableNames', { ...
            'Scenario', ...
            'ModelClass', ...
            'RMSE', ...
            'RMSECI95', ...
            'R2', ...
            'R2CI95', ...
            'TopArmAccuracy', ...
            'TopArmAccuracyCI95', ...
            'OracleCapture', ...
            'OracleCaptureCI95', ...
            'RankingRegret', ...
            'RankingRegretCI95'});

end


function output = aggregate_d2(raw)

    scenarios = unique(raw.Scenario, "stable");
    modes = unique(raw.ExpertMode, "stable");

    rows = cell(numel(scenarios) * numel(modes), 1);
    index = 0;

    for s = 1:numel(scenarios)
        for m = 1:numel(modes)

            mask = ...
                raw.Scenario == scenarios(s) ...
                & raw.ExpertMode == modes(m);

            subset = raw(mask, :);
            index = index + 1;

            [fixedCapture, fixedCI] = ...
                mean_ci(subset.FixedOracleCapture);

            [dynamicCapture, dynamicCI] = ...
                mean_ci(subset.DynamicExpertCapture);

            [fixedReward, fixedRewardCI] = ...
                mean_ci(subset.BestFixedReward);

            [dynamicReward, dynamicRewardCI] = ...
                mean_ci(subset.DynamicExpertReward);

            rows{index} = table( ...
                scenarios(s), ...
                modes(m), ...
                mean(subset.NumExperts), ...
                fixedReward, ...
                fixedRewardCI, ...
                dynamicReward, ...
                dynamicRewardCI, ...
                mean(subset.DynamicArmReward), ...
                fixedCapture, ...
                fixedCI, ...
                dynamicCapture, ...
                dynamicCI, ...
                'VariableNames', { ...
                    'Scenario', ...
                    'ExpertMode', ...
                    'NumExperts', ...
                    'BestFixedReward', ...
                    'BestFixedRewardCI95', ...
                    'DynamicExpertReward', ...
                    'DynamicExpertRewardCI95', ...
                    'DynamicArmReward', ...
                    'FixedOracleCapture', ...
                    'FixedOracleCaptureCI95', ...
                    'DynamicExpertCapture', ...
                    'DynamicExpertCaptureCI95'});
        end
    end

    output = vertcat(rows{:});

end


function [meanValue, ci95] = mean_ci(values)

    values = values(:);
    values = values(isfinite(values));

    if isempty(values)
        meanValue = NaN;
        ci95 = NaN;
        return;
    end

    meanValue = mean(values);

    if numel(values) <= 1
        ci95 = NaN;
    else
        ci95 = ...
            1.96 * std(values) / sqrt(numel(values));
    end

end


function ensure_folder(folderPath)

    if ~isfolder(folderPath)
        mkdir(folderPath);
    end

end
