function write_diagnostic_verdict( ...
    outputPath, tableD1, tableD2, tableD3, tableD4)
%WRITE_DIAGNOSTIC_VERDICT Evidence-based automatic diagnostic summary.

    fileId = fopen(outputPath, "w");

    if fileId < 0
        error("Could not create diagnostic verdict.");
    end

    cleanup = onCleanup(@() fclose(fileId));

    linearCapture = lookup_value( ...
        tableD1, "none", "linear", "OracleCapture");

    nonlinearCapture = lookup_value( ...
        tableD1, "none", "nonlinear", "OracleCapture");

    hybridFixed = lookup_value( ...
        tableD2, "none", "hybrid", "FixedOracleCapture");

    hybridDynamic = lookup_value( ...
        tableD2, "none", "hybrid", "DynamicExpertCapture");

    linearFixed = lookup_value( ...
        tableD2, "none", "linear", "FixedOracleCapture");

    partitionFixed = lookup_value( ...
        tableD2, "none", "partition", "FixedOracleCapture");

    lcNoAttack = lookup_variant( ...
        tableD3, "none", "LC-Tsallis-INF-Online", "GoodputMbps");

    hybridNoAttack = lookup_variant( ...
        tableD3, "none", "PACT-Hybrid", "GoodputMbps");

    gamma0NoAttack = lookup_variant( ...
        tableD3, "none", "PACT-Hybrid-Gamma0", "GoodputMbps");

    gamma25NoAttack = lookup_variant( ...
        tableD3, "none", "PACT-Hybrid-Gamma25", "GoodputMbps");

    linearOnlyNoAttack = lookup_variant( ...
        tableD3, "none", "PACT-Linear", "GoodputMbps");

    partitionOnlyNoAttack = lookup_variant( ...
        tableD3, "none", "PACT-Partition", "GoodputMbps");

    hybridAggregationGap = lookup_variant( ...
        tableD3, "none", "PACT-Hybrid", "AggregationGap");

    hybridRepresentationGap = lookup_variant( ...
        tableD3, "none", "PACT-Hybrid", "RepresentationGap");

    nonlinearTasks = [ ...
        "interaction", "xor", "band_pass", "weight_flip"];

    nonlinearHybridCapture = NaN(numel(nonlinearTasks), 1);

    for index = 1:numel(nonlinearTasks)
        nonlinearHybridCapture(index) = lookup_synthetic( ...
            tableD4, nonlinearTasks(index), ...
            "hybrid", "FixedOracleCapture");
    end

    fprintf(fileId, "# PACT-AFH model diagnostic verdict\n\n");

    fprintf(fileId, "## 1. Is the current environment linear-friendly?\n\n");
    fprintf(fileId, ...
        "- Linear test reward capture: **%.4f**\n", ...
        linearCapture);
    fprintf(fileId, ...
        "- Rich nonlinear-basis capture: **%.4f**\n", ...
        nonlinearCapture);
    fprintf(fileId, ...
        "- Nonlinear gain over linear: **%.4f**\n\n", ...
        nonlinearCapture - linearCapture);

    if isfinite(linearCapture) ...
            && isfinite(nonlinearCapture) ...
            && linearCapture >= 0.95 ...
            && nonlinearCapture - linearCapture <= 0.02

        fprintf(fileId, ...
            "**Evidence:** the present stochastic communication " ...
            "environment is strongly linear-friendly. This does not " ...
            "prove that real wireless environments are globally linear; " ...
            "it means the current features already rank channels almost " ...
            "linearly.\n\n");

    elseif isfinite(nonlinearCapture) ...
            && nonlinearCapture - linearCapture >= 0.05

        fprintf(fileId, ...
            "**Evidence:** nonlinear feature structure materially " ...
            "improves channel ranking in the current environment.\n\n");

    else
        fprintf(fileId, ...
            "**Evidence:** the current environment is neither clearly " ...
            "linear nor strongly nonlinear under this test. Inspect " ...
            "Table D1 and its confidence intervals.\n\n");
    end

    fprintf(fileId, "## 2. Is the current expert bank expressive enough?\n\n");
    fprintf(fileId, ...
        "- Best fixed partition-expert capture: **%.4f**\n", ...
        partitionFixed);
    fprintf(fileId, ...
        "- Best fixed linear-expert capture: **%.4f**\n", ...
        linearFixed);
    fprintf(fileId, ...
        "- Best fixed hybrid-expert capture: **%.4f**\n", ...
        hybridFixed);
    fprintf(fileId, ...
        "- Per-round best hybrid-expert capture: **%.4f**\n\n", ...
        hybridDynamic);

    if isfinite(hybridFixed) && hybridFixed < 0.90
        fprintf(fileId, ...
            "**Evidence:** there is a substantial fixed-class " ...
            "representation gap. Tuning FTRL alone cannot remove it.\n\n");
    elseif isfinite(hybridFixed)
        fprintf(fileId, ...
            "**Evidence:** the fixed hybrid class captures most of the " ...
            "dynamic-arm oracle. Online learning/exploration deserves " ...
            "closer attention than class expansion.\n\n");
    end

    fprintf(fileId, "## 3. Is the online gap caused by exploration or aggregation?\n\n");
    fprintf(fileId, ...
        "- LC-Online goodput without active jammer: **%.4f Mbps**\n", ...
        lcNoAttack);
    fprintf(fileId, ...
        "- PACT-Hybrid goodput: **%.4f Mbps**\n", ...
        hybridNoAttack);
    fprintf(fileId, ...
        "- PACT-Linear goodput: **%.4f Mbps**\n", ...
        linearOnlyNoAttack);
    fprintf(fileId, ...
        "- PACT-Partition goodput: **%.4f Mbps**\n", ...
        partitionOnlyNoAttack);
    fprintf(fileId, ...
        "- Hybrid with gamma=0: **%.4f Mbps**\n", ...
        gamma0NoAttack);
    fprintf(fileId, ...
        "- Hybrid with 0.25 exploration scale: **%.4f Mbps**\n", ...
        gamma25NoAttack);
    fprintf(fileId, ...
        "- Hybrid aggregation gap: **%.4f reward/round**\n", ...
        hybridAggregationGap);
    fprintf(fileId, ...
        "- Hybrid representation gap: **%.4f reward/round**\n\n", ...
        hybridRepresentationGap);

    if isfinite(gamma0NoAttack) ...
            && isfinite(hybridNoAttack) ...
            && gamma0NoAttack > 1.02 * hybridNoAttack

        fprintf(fileId, ...
            "**Evidence:** the default exploration schedule costs more " ...
            "than 2%% goodput. Exploration reduction is a justified " ...
            "optimization candidate.\n\n");
    else
        fprintf(fileId, ...
            "**Evidence:** exploration does not explain a large share of " ...
            "the communication gap under the tested horizon.\n\n");
    end

    if isfinite(linearOnlyNoAttack) ...
            && isfinite(hybridNoAttack) ...
            && linearOnlyNoAttack > 1.02 * hybridNoAttack

        fprintf(fileId, ...
            "**Evidence:** adding partition experts dilutes useful linear " ...
            "experts at this horizon. A master over adaptive learners or " ...
            "family-level aggregation should be considered.\n\n");
    end

    fprintf(fileId, "## 4. Are the current partition experts genuinely nonlinear?\n\n");

    for index = 1:numel(nonlinearTasks)
        fprintf(fileId, ...
            "- Hybrid fixed capture on `%s`: **%.4f**\n", ...
            nonlinearTasks(index), ...
            nonlinearHybridCapture(index));
    end

    meanNonlinearCapture = mean( ...
        nonlinearHybridCapture, "omitnan");

    fprintf(fileId, ...
        "\nMean nonlinear-task capture: **%.4f**\n\n", ...
        meanNonlinearCapture);

    if isfinite(meanNonlinearCapture) ...
            && meanNonlinearCapture < 0.85

        fprintf(fileId, ...
            "**Evidence:** the present quantized, nonnegative additive " ...
            "experts are not a general nonlinear model. Quantization " ...
            "alone does not represent XOR, band-pass, or regime-dependent " ...
            "weight reversals. Dynamic or locally parameterized experts " ...
            "are technically justified.\n\n");
    else
        fprintf(fileId, ...
            "**Evidence:** the current expert bank represents the tested " ...
            "nonlinear structures reasonably well. Dynamic experts are " ...
            "not yet required by this audit alone.\n\n");
    end

    fprintf(fileId, "## Decision rule\n\n");
    fprintf(fileId, ...
        "Do not modify the main PACT mechanism until Tables D1-D4 are " ...
        "reviewed. If the main issue is representation, add adaptive " ...
        "linear/nonlinear base learners. If the main issue is aggregation " ...
        "or exploration, retain the expert class and tune the online " ...
        "master. If both appear, use a family-level or CORRAL-style " ...
        "master rather than adding more static experts indiscriminately.\n");

end


function value = lookup_value( ...
    inputTable, scenario, className, variableName)

    mask = inputTable.Scenario == string(scenario);

    if ismember("ModelClass", ...
            string(inputTable.Properties.VariableNames))

        mask = mask ...
            & inputTable.ModelClass == string(className);

    elseif ismember("ExpertMode", ...
            string(inputTable.Properties.VariableNames))

        mask = mask ...
            & inputTable.ExpertMode == string(className);

    else
        error("Diagnostic table has no class column.");
    end

    value = first_or_nan( ...
        inputTable.(variableName)(mask));

end


function value = lookup_variant( ...
    inputTable, adversary, variant, variableName)

    mask = ...
        inputTable.Adversary == string(adversary) ...
        & inputTable.Variant == string(variant);

    value = first_or_nan( ...
        inputTable.(variableName)(mask));

end


function value = lookup_synthetic( ...
    inputTable, task, mode, variableName)

    mask = ...
        inputTable.Task == string(task) ...
        & inputTable.ExpertMode == string(mode);

    value = first_or_nan( ...
        inputTable.(variableName)(mask));

end


function value = first_or_nan(values)

    if isempty(values)
        value = NaN;
    else
        value = values(1);
    end

end
